language: php
php:
  - "5.4"
before_install:
- composer self-update
- pecl install oauth
before_script:
- composer install
- mkdir -p build/logs
script:
- phpunit --coverage-clover build/logs/clover.xml
